services:
  qui-paie:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qui-paie
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qui-paie.rule=Host(`kouyfay.teamghosts.team`)"
      - "traefik.http.routers.qui-paie.entrypoints=websecure"
      - "traefik.http.routers.qui-paie.tls.certresolver=letsencrypt"
      - "traefik.http.services.qui-paie.loadbalancer.server.port=80"
    networks:
      - dokploy-network
    healthcheck:
      disable: true

networks:
  dokploy-network:
    external: true
